backend:
  name: github
  repo: irinashev28-ux/akademiya-mebli
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth


media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "pages"
    label: "Страницы"
    files:
      - label: "Главная страница"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Заголовок", name: "title", widget: "string" }
          - { label: "Текст", name: "body", widget: "markdown" }
          - { label: "Фото", name: "image", widget: "image" }
site_url: https://irinashev28-ux.github.io/akademiya-mebli
